import {
  CampusBuilding,
  CampusHealthScore,
  InsightItem,
  Issue,
  NotificationItem,
  User,
} from '@/types';

export const MALDA_COLLEGE_COORDINATES = {
  lat: 25.0088,
  lng: 88.1394,
};

export const MOCK_BUILDINGS: CampusBuilding[] = [
  {
    id: 'bldg-vidyasagar',
    name: 'Vidyasagar Bhavan (Science & Tech Block)',
    code: 'VID-BHAVAN',
    lat: 25.0091,
    lng: 88.1388,
    departments: ['Physics', 'Computer Science', 'Mathematics', 'Chemistry'],
    floors: 3,
    description: 'Houses primary science departments, computer laboratories, and lecture halls.',
    type: 'ACADEMIC',
  },
  {
    id: 'bldg-centenary',
    name: 'Centenary Building (Administration & IQAC)',
    code: 'CENT-ADM',
    lat: 25.0085,
    lng: 88.1392,
    departments: ['Principal Office', 'IQAC', 'Controller of Examinations', 'Accounts'],
    floors: 3,
    description: 'Central administrative headquarters, council rooms, and smart seminar halls.',
    type: 'ADMINISTRATIVE',
  },
  {
    id: 'bldg-library',
    name: 'Central Library & Digital Knowledge Center',
    code: 'LIB-CENTRAL',
    lat: 25.0089,
    lng: 88.1402,
    departments: ['Central Library', 'Digital Archives', 'E-Learning Center'],
    floors: 2,
    description: 'Over 60,000 volumes, digital reading room, high-speed terminal section.',
    type: 'STUDENT_FACILITY',
  },
  {
    id: 'bldg-rabindra',
    name: 'Rabindra Bhavan (Auditorium & Arts Block)',
    code: 'RAB-BHAVAN',
    lat: 25.0094,
    lng: 88.1398,
    departments: ['Bengali', 'English', 'History', 'Philosophy', 'Cultural Cell'],
    floors: 2,
    description: '800-capacity auditorium, language seminar rooms, and humanities faculties.',
    type: 'ACADEMIC',
  },
  {
    id: 'bldg-bca-it',
    name: 'BCA & IT Innovation Complex',
    code: 'BCA-COMPLEX',
    lat: 25.0082,
    lng: 88.1385,
    departments: ['BCA', 'Networking Hub', 'Server Infrastructure'],
    floors: 2,
    description: 'Dedicated software engineering labs, server room, and campus fiber distribution point.',
    type: 'LABORATORY',
  },
  {
    id: 'bldg-canteen',
    name: 'Student Common Room & Cafeteria',
    code: 'CANTEEN-SCR',
    lat: 25.0081,
    lng: 88.1401,
    departments: ['Student Welfare', 'Canteen Committee'],
    floors: 1,
    description: 'Dining hall, recreation space, and student union helpdesk.',
    type: 'STUDENT_FACILITY',
  },
  {
    id: 'bldg-hostel-boys',
    name: 'Kazi Nazrul Islam Bhavan (Boys Hostel)',
    code: 'HOSTEL-BOYS',
    lat: 25.0076,
    lng: 88.1381,
    departments: ['Hostel Superintendent Office'],
    floors: 3,
    description: 'Student accommodation, residential mess, and study hall.',
    type: 'RESIDENTIAL',
  },
  {
    id: 'bldg-sports',
    name: 'College Sports Pavilion & Gymnasium',
    code: 'SPORTS-PAV',
    lat: 25.0098,
    lng: 88.1382,
    departments: ['Physical Education', 'NSS', 'NCC Cell'],
    floors: 1,
    description: 'Indoor multi-gymnasium, athletic changing rooms, and sports registry.',
    type: 'STUDENT_FACILITY',
  },
];

export const MOCK_USERS: Record<string, User> = {
  student: {
    id: 'usr-student-01',
    name: 'Ananya Sen',
    email: 'ananya.sen@malda-student.ac.in',
    role: 'STUDENT',
    studentId: 'MC-2024-CS-042',
    department: 'Computer Science (Hons.)',
    phone: '+91 98321 45012',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  staff: {
    id: 'usr-staff-01',
    name: 'Subhashish Roy',
    email: 'subhashish.roy@maldacollege.ac.in',
    role: 'STAFF',
    staffId: 'MC-TECH-018',
    department: 'Electrical & Facility Operations',
    phone: '+91 94340 77189',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  deptAdmin: {
    id: 'usr-dept-01',
    name: 'Dr. Pradeep Mukherjee',
    email: 'p.mukherjee@maldacollege.ac.in',
    role: 'DEPARTMENT_ADMIN',
    staffId: 'MC-FAC-009',
    department: 'Head, Academic Infrastructure & IQAC',
    phone: '+91 94341 88204',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  superAdmin: {
    id: 'usr-admin-01',
    name: 'Principal Secretariat',
    email: 'principal@maldacollege.ac.in',
    role: 'SUPER_ADMIN',
    staffId: 'MC-EXEC-001',
    department: 'Malda College Governing Council',
    phone: '+91 3512 220 529',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
};

export const INITIAL_MOCK_ISSUES: Issue[] = [
  {
    id: 'iss-001',
    ticketNumber: 'MC-2027-0104',
    title: 'Ceiling Projector intermittently flickering & HDMI signal dropping in Centenary Hall',
    description: 'During 3rd year Computer Science and Mathematics lectures, the ceiling mounted BenQ projector in Room 204 shuts off after 10-15 minutes of operation. The wall HDMI plate appears loose with bent contact pins.',
    category: 'FACILITY_CLASSROOM',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    location: {
      building: 'Centenary Building (Administration & IQAC)',
      buildingCode: 'CENT-ADM',
      floor: '2nd Floor',
      roomOrLandmark: 'Room 204 (Smart Lecture Theatre)',
      coordinates: { lat: 25.0085, lng: 88.1392 },
    },
    reporter: {
      id: 'usr-student-01',
      name: 'Ananya Sen',
      role: 'STUDENT',
      studentId: 'MC-2024-CS-042',
      department: 'Computer Science',
    },
    assignedTo: {
      id: 'usr-staff-01',
      name: 'Subhashish Roy',
      department: 'Electrical & Facility Operations',
      phone: '+91 94340 77189',
    },
    department: 'Electrical & Facility Operations',
    images: [
      'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&auto=format&fit=crop&q=80',
    ],
    upvotes: 14,
    upvotedBy: ['usr-student-01', 'usr-std-02', 'usr-std-03'],
    createdAt: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    aiAnalysis: {
      detectedCategory: 'FACILITY_CLASSROOM',
      suggestedSeverity: 'HIGH',
      suggestedPriority: 'HIGH',
      confidence: 0.92,
      summary: 'Recurring thermal shutdown or loose AV connectivity affecting daily undergraduate lecture delivery.',
      suggestedDepartment: 'Electrical & Facility Operations',
      possibleDuplicates: [
        {
          ticketNumber: 'MC-2027-0062',
          id: 'iss-old-01',
          title: 'Projector remote missing and lamp signal error in Room 204',
          similarityScore: 0.74,
          status: 'RESOLVED',
        },
      ],
      urgencyFactors: [
        'Affects core classroom instruction schedule',
        'Multiple faculty lectures scheduled today',
        'Reported by 14 students',
      ],
      gatewayProvider: 'CampusPulse AI Engine (Groq Llama-3-70b)',
      analyzedAt: new Date(Date.now() - 35 * 3600 * 1000).toISOString(),
    },
    timeline: [
      {
        id: 'tl-1',
        status: 'REPORTED',
        label: 'Issue Lodged by Student',
        description: 'Report filed with classroom location and photo evidence.',
        timestamp: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
        actor: { name: 'Ananya Sen', role: 'Student (CS)' },
      },
      {
        id: 'tl-2',
        status: 'AI_ANALYZED',
        label: 'AI Operational Triage Complete',
        description: 'Auto-categorized as FACILITY_CLASSROOM. Suggested Priority: HIGH (Confidence: 92%). Flagged possible hardware fatigue.',
        timestamp: new Date(Date.now() - 35 * 3600 * 1000).toISOString(),
        actor: { name: 'CampusPulse AI Triage', role: 'Automated Gateway' },
      },
      {
        id: 'tl-3',
        status: 'ASSIGNED',
        label: 'Assigned to Electrical & Facility Operations',
        description: 'Dispatched to technician Subhashish Roy for AV inspection and HDMI plate replacement.',
        timestamp: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
        actor: { name: 'Dr. Pradeep Mukherjee', role: 'Academic Infrastructure Admin' },
      },
      {
        id: 'tl-4',
        status: 'IN_PROGRESS',
        label: 'Technician on Site',
        description: 'Technician inspected projector cooling fan; replacement shielded HDMI cable procured from store.',
        timestamp: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
        actor: { name: 'Subhashish Roy', role: 'Staff Technician' },
      },
    ],
    comments: [
      {
        id: 'c-1',
        issueId: 'iss-001',
        author: {
          id: 'usr-student-01',
          name: 'Ananya Sen',
          role: 'STUDENT',
          department: 'Computer Science',
        },
        content: 'Prof. Banerjee could not finish the database slides today because of the black screen. Hoping this can be resolved before tomorrow 10 AM class.',
        createdAt: new Date(Date.now() - 30 * 3600 * 1000).toISOString(),
      },
      {
        id: 'c-2',
        issueId: 'iss-001',
        author: {
          id: 'usr-staff-01',
          name: 'Subhashish Roy',
          role: 'STAFF',
          department: 'Electrical & Facility Operations',
        },
        content: 'Inspected the ceiling mount. The filter was clogged causing overheat protection shutdown, and the wall jack has physical fatigue. Cleaning filter and installing new gold-plated coupler today.',
        createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'iss-002',
    ticketNumber: 'MC-2027-0108',
    title: 'Water cooler overflow and pipe leakage on 2nd Floor corridor, Vidyasagar Bhavan',
    description: 'The stainless steel drinking water cooler outside the Physics Optics Lab is leaking from its drainage pipe. Water has pooled across the corridor, creating a slipping hazard near the stairs.',
    category: 'PLUMBING',
    priority: 'HIGH',
    status: 'ASSIGNED',
    location: {
      building: 'Vidyasagar Bhavan (Science & Tech Block)',
      buildingCode: 'VID-BHAVAN',
      floor: '2nd Floor',
      roomOrLandmark: 'Corridor outside Optics Lab 208',
      coordinates: { lat: 25.0091, lng: 88.1388 },
    },
    reporter: {
      id: 'usr-std-05',
      name: 'Rohan Karmakar',
      role: 'STUDENT',
      studentId: 'MC-2025-PH-019',
      department: 'Physics',
    },
    assignedTo: {
      id: 'usr-staff-02',
      name: 'Biren Mondal',
      department: 'Civil Works & Plumbing',
      phone: '+91 94342 11982',
    },
    department: 'Civil Works & Plumbing',
    images: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
    ],
    upvotes: 9,
    upvotedBy: ['usr-student-01', 'usr-std-05'],
    createdAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    aiAnalysis: {
      detectedCategory: 'PLUMBING',
      suggestedSeverity: 'HIGH',
      suggestedPriority: 'HIGH',
      confidence: 0.95,
      summary: 'Corridor water accumulation adjacent to high-traffic lab stairs posing physical slip hazard.',
      suggestedDepartment: 'Civil Works & Plumbing',
      possibleDuplicates: [],
      urgencyFactors: [
        'Pedestrian slip and fall hazard near staircase',
        'Potential electrical proximity hazard',
      ],
      gatewayProvider: 'CampusPulse AI Engine',
      analyzedAt: new Date(Date.now() - 13 * 3600 * 1000).toISOString(),
    },
    timeline: [
      {
        id: 'tl-201',
        status: 'REPORTED',
        label: 'Reported by Student',
        description: 'Hazard report submitted with location tag.',
        timestamp: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
        actor: { name: 'Rohan Karmakar', role: 'Student (Physics)' },
      },
      {
        id: 'tl-202',
        status: 'AI_ANALYZED',
        label: 'Safety Hazard Identified by AI',
        description: 'Flagged as high-urgency physical safety hazard due to stair proximity.',
        timestamp: new Date(Date.now() - 13 * 3600 * 1000).toISOString(),
        actor: { name: 'CampusPulse AI Triage', role: 'Automated Gateway' },
      },
      {
        id: 'tl-203',
        status: 'ASSIGNED',
        label: 'Assigned to Civil & Plumbing Cell',
        description: 'Assigned to plumber Biren Mondal; caretaker instructed to place cautionary cone.',
        timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
        actor: { name: 'Dr. Pradeep Mukherjee', role: 'Department Admin' },
      },
    ],
    comments: [],
  },
  {
    id: 'iss-003',
    ticketNumber: 'MC-2027-0112',
    title: 'High latency and frequent SSID dropouts in Central Library Digital Research Section',
    description: 'Students preparing for upcoming semester projects are unable to connect to the "MaldaCollege_Student_5G" access point in the eastern reading hall. Pings to gateway time out intermittently.',
    category: 'IT_NETWORK',
    priority: 'MEDIUM',
    status: 'REPORTED',
    location: {
      building: 'Central Library & Digital Knowledge Center',
      buildingCode: 'LIB-CENTRAL',
      floor: '1st Floor',
      roomOrLandmark: 'East Digital Research Hall (Tables 12-24)',
      coordinates: { lat: 25.0089, lng: 88.1402 },
    },
    reporter: {
      id: 'usr-student-01',
      name: 'Ananya Sen',
      role: 'STUDENT',
      studentId: 'MC-2024-CS-042',
      department: 'Computer Science',
    },
    department: 'IT & Network Cell',
    images: [],
    upvotes: 21,
    upvotedBy: ['usr-student-01', 'usr-std-07', 'usr-std-08', 'usr-std-09'],
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    aiAnalysis: {
      detectedCategory: 'IT_NETWORK',
      suggestedSeverity: 'MEDIUM',
      suggestedPriority: 'MEDIUM',
      confidence: 0.88,
      summary: 'Likely channel saturation or PoE switch port power reset needed for Aruba AP in reading hall.',
      suggestedDepartment: 'IT & Network Cell',
      possibleDuplicates: [
        {
          ticketNumber: 'MC-2027-0098',
          id: 'iss-prev-lib',
          title: 'Library e-journal terminal IP configuration error',
          similarityScore: 0.61,
          status: 'RESOLVED',
        },
      ],
      urgencyFactors: [
        'Affects examination preparation and digital journal access',
        '21 student endorsements within 6 hours',
      ],
      gatewayProvider: 'CampusPulse AI Engine',
      analyzedAt: new Date(Date.now() - 5.8 * 3600 * 1000).toISOString(),
    },
    timeline: [
      {
        id: 'tl-301',
        status: 'REPORTED',
        label: 'Issue Submitted',
        description: 'Network connectivity ticket created with affected SSID and location.',
        timestamp: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
        actor: { name: 'Ananya Sen', role: 'Student' },
      },
      {
        id: 'tl-302',
        status: 'AI_ANALYZED',
        label: 'AI Network Triage',
        description: 'AI detected IT_NETWORK; recommended priority MEDIUM, auto-routed to IT Cell queue.',
        timestamp: new Date(Date.now() - 5.8 * 3600 * 1000).toISOString(),
        actor: { name: 'CampusPulse AI Triage', role: 'Automated Gateway' },
      },
    ],
    comments: [],
  },
  {
    id: 'iss-004',
    ticketNumber: 'MC-2027-0119',
    title: 'Main circuit breaker sparking in Chemistry Lab 3 Fume Exhaust board',
    description: 'Audible arcing and intermittent burning smell noticed from sub-distribution board DB-C3 behind fume chamber 2 during organic chemistry practical class. Lab assistant has temporarily flipped master isolator.',
    category: 'ELECTRICAL',
    priority: 'CRITICAL',
    status: 'IN_PROGRESS',
    location: {
      building: 'Vidyasagar Bhavan (Science & Tech Block)',
      buildingCode: 'VID-BHAVAN',
      floor: '1st Floor',
      roomOrLandmark: 'Chemistry Lab 3 (Inorganic/Organic)',
      coordinates: { lat: 25.0091, lng: 88.1388 },
    },
    reporter: {
      id: 'usr-fac-chem',
      name: 'Dr. Tanmay Dutta',
      role: 'STAFF',
      department: 'Chemistry',
    },
    assignedTo: {
      id: 'usr-staff-01',
      name: 'Subhashish Roy',
      department: 'Electrical & Facility Operations',
      phone: '+91 94340 77189',
    },
    department: 'Electrical & Facility Operations',
    images: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    ],
    upvotes: 28,
    upvotedBy: ['usr-student-01'],
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    aiAnalysis: {
      detectedCategory: 'ELECTRICAL',
      suggestedSeverity: 'CRITICAL',
      suggestedPriority: 'CRITICAL',
      confidence: 0.98,
      summary: 'Electrical arcing with combustion hazard in chemical laboratory environment. Immediate physical isolation mandated.',
      suggestedDepartment: 'Electrical & Facility Operations',
      possibleDuplicates: [],
      urgencyFactors: [
        'Active electrical fire risk',
        'Presence of volatile reagents in laboratory environment',
        'Academic activity halted in affected wing',
      ],
      gatewayProvider: 'CampusPulse AI Engine',
      analyzedAt: new Date(Date.now() - 2.9 * 3600 * 1000).toISOString(),
    },
    timeline: [
      {
        id: 'tl-401',
        status: 'REPORTED',
        label: 'Emergency Alert Logged',
        description: 'Faculty logged electrical sparking event in Chemistry Lab.',
        timestamp: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
        actor: { name: 'Dr. Tanmay Dutta', role: 'Faculty Member' },
      },
      {
        id: 'tl-402',
        status: 'AI_ANALYZED',
        label: 'AI Priority Escalation: CRITICAL',
        description: 'System automatically triggered High Severity Protocol due to electrical arc in lab setting.',
        timestamp: new Date(Date.now() - 2.9 * 3600 * 1000).toISOString(),
        actor: { name: 'CampusPulse AI Guard', role: 'Safety Automation' },
      },
      {
        id: 'tl-403',
        status: 'ASSIGNED',
        label: 'Immediate Emergency Dispatch',
        description: 'Auto-dispatched to Senior Electrical Officer Subhashish Roy. SMS alert sent.',
        timestamp: new Date(Date.now() - 2.5 * 3600 * 1000).toISOString(),
        actor: { name: 'Principal Secretariat', role: 'Super Admin' },
      },
      {
        id: 'tl-404',
        status: 'IN_PROGRESS',
        label: 'Breaker Replacement & Thermal Scan',
        description: 'Sub-breaker isolated. Thermal imaging showed 63A MCB terminal degradation. New Schneider MCB being installed.',
        timestamp: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
        actor: { name: 'Subhashish Roy', role: 'Staff Technician' },
      },
    ],
    comments: [
      {
        id: 'c-401',
        issueId: 'iss-004',
        author: {
          id: 'usr-staff-01',
          name: 'Subhashish Roy',
          role: 'STAFF',
          department: 'Electrical & Facility Operations',
        },
        content: 'Work in progress. Feeder line isolated safely. Testing line load before restoring power to fume extractors.',
        createdAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'iss-005',
    ticketNumber: 'MC-2027-0095',
    title: 'Faulty motor and vibration in College Canteen main kitchen exhaust',
    description: 'Heavy grease build-up and noisy vibration in the primary exhaust chimney was filling the indoor dining area with cooking fumes during lunch peak hours.',
    category: 'SANITATION',
    priority: 'MEDIUM',
    status: 'RESOLVED',
    location: {
      building: 'Student Common Room & Cafeteria',
      buildingCode: 'CANTEEN-SCR',
      floor: 'Ground Floor',
      roomOrLandmark: 'Main Kitchen Exhaust Duct',
      coordinates: { lat: 25.0081, lng: 88.1401 },
    },
    reporter: {
      id: 'usr-std-canteen',
      name: 'Priyanka Das',
      role: 'STUDENT',
      department: 'English',
    },
    assignedTo: {
      id: 'usr-staff-03',
      name: 'Kallol Sarkar',
      department: 'Civil Works & Sanitation',
    },
    department: 'Civil Works & Sanitation',
    images: [],
    upvotes: 18,
    upvotedBy: [],
    createdAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    timeline: [
      {
        id: 'tl-501',
        status: 'REPORTED',
        label: 'Report Submitted',
        description: 'Student complaint regarding smoke and ventilation.',
        timestamp: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
        actor: { name: 'Priyanka Das', role: 'Student' },
      },
      {
        id: 'tl-502',
        status: 'ASSIGNED',
        label: 'Assigned to Sanitation Wing',
        description: 'Assigned for industrial chimney cleaning.',
        timestamp: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
        actor: { name: 'Canteen Committee', role: 'Staff' },
      },
      {
        id: 'tl-503',
        status: 'RESOLUTION_SUBMITTED',
        label: 'Maintenance Completed',
        description: 'Exhaust motor replaced, fan blades degreased and balanced.',
        timestamp: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
        actor: { name: 'Kallol Sarkar', role: 'Sanitation Lead' },
      },
      {
        id: 'tl-504',
        status: 'RESOLVED',
        label: 'Resolved & Verified',
        description: 'Smoke dispersion verified normal during lunch service.',
        timestamp: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
        actor: { name: 'Principal Secretariat', role: 'Super Admin' },
      },
    ],
    comments: [],
  },
  {
    id: 'iss-006',
    ticketNumber: 'MC-2027-0088',
    title: 'Workstation 14 continuous beep and memory POST failure in BCA Lab 2',
    description: 'PC number 14 in BCA Laboratory 2 fails to boot into Ubuntu OS, giving 3 short beeps indicating RAM seat defect.',
    category: 'LAB_EQUIPMENT',
    priority: 'LOW',
    status: 'RESOLVED',
    location: {
      building: 'BCA & IT Innovation Complex',
      buildingCode: 'BCA-COMPLEX',
      floor: '1st Floor',
      roomOrLandmark: 'BCA Practical Lab 2 (Workstation 14)',
      coordinates: { lat: 25.0082, lng: 88.1385 },
    },
    reporter: {
      id: 'usr-student-01',
      name: 'Ananya Sen',
      role: 'STUDENT',
      studentId: 'MC-2024-CS-042',
      department: 'Computer Science',
    },
    department: 'IT & Network Cell',
    images: [],
    upvotes: 4,
    upvotedBy: [],
    createdAt: new Date(Date.now() - 96 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    timeline: [],
    comments: [],
  },
  {
    id: 'iss-007',
    ticketNumber: 'MC-2027-0125',
    title: 'Loose wooden handrail on eastern emergency staircase, Vidyasagar Bhavan',
    description: 'The support brackets anchoring the handrail to the masonry between the 1st and 2nd floors have pulled out. Students rushing between lectures have almost lost balance.',
    category: 'SAFETY_SECURITY',
    priority: 'HIGH',
    status: 'REPORTED',
    location: {
      building: 'Vidyasagar Bhavan (Science & Tech Block)',
      buildingCode: 'VID-BHAVAN',
      floor: 'Between 1st & 2nd Floor',
      roomOrLandmark: 'East Fire Exit Stairwell',
      coordinates: { lat: 25.0091, lng: 88.1388 },
    },
    reporter: {
      id: 'usr-student-01',
      name: 'Ananya Sen',
      role: 'STUDENT',
      studentId: 'MC-2024-CS-042',
      department: 'Computer Science',
    },
    department: 'Civil Works & Plumbing',
    images: [],
    upvotes: 8,
    upvotedBy: ['usr-student-01'],
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    aiAnalysis: {
      detectedCategory: 'SAFETY_SECURITY',
      suggestedSeverity: 'HIGH',
      suggestedPriority: 'HIGH',
      confidence: 0.94,
      summary: 'Structural handrail failure in high-transit academic stairwell presenting acute physical fall hazard.',
      suggestedDepartment: 'Civil Works & Plumbing',
      possibleDuplicates: [],
      urgencyFactors: [
        'Primary transit pathway for Science department students',
        'Physical trauma risk if unaddressed',
      ],
      gatewayProvider: 'CampusPulse AI Engine',
      analyzedAt: new Date(Date.now() - 1.9 * 3600 * 1000).toISOString(),
    },
    timeline: [
      {
        id: 'tl-701',
        status: 'REPORTED',
        label: 'Incident Reported',
        description: 'Report filed with photo evidence.',
        timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
        actor: { name: 'Ananya Sen', role: 'Student' },
      },
      {
        id: 'tl-702',
        status: 'AI_ANALYZED',
        label: 'AI Safety Assessment Complete',
        description: 'Auto-categorized as SAFETY_SECURITY with suggested HIGH priority.',
        timestamp: new Date(Date.now() - 1.9 * 3600 * 1000).toISOString(),
        actor: { name: 'CampusPulse AI Triage', role: 'Automated Gateway' },
      },
    ],
    comments: [],
  },
];

export const MOCK_CAMPUS_HEALTH: CampusHealthScore = {
  overall: 82,
  resolutionPerformance: 88,
  openIssueLoad: 76,
  criticalSeverityIndex: 90,
  recurringFaultIndex: 74,
  statusLabel: 'STABLE',
  trailingDays: 14,
  disclaimer:
    'Campus Health Score is an operational indicator computed from 14-day trailing maintenance throughput, open severity weights, and recurring fault frequencies across Malda College facilities. Not a predictive statistical guarantee.',
};

export const MOCK_INSIGHTS: InsightItem[] = [
  {
    id: 'ins-01',
    type: 'RECURRING_PATTERN',
    title: 'Centenary Hall Projector & AV Cables Show Monthly Degradation Trend',
    description: 'Three distinct projector failure tickets have occurred in Room 204 and Room 201 within 30 days, primarily traced to loose wall HDMI conduit and filter overheating.',
    affectedArea: 'Centenary Building (Rooms 201 & 204)',
    detectedDate: 'Last 30 Days',
    linkedTickets: ['MC-2027-0104', 'MC-2027-0062'],
    severity: 'WARNING',
    actionableRecommendation: 'Recommend scheduling an institutional overhaul of ceiling AV cabling and installing semi-annual thermal filter cleaning contracts before the semester exams.',
    metricImpact: 'Could prevent ~8 lecture interruptions per quarter',
  },
  {
    id: 'ins-02',
    type: 'LOCATION_HOTSPOT',
    title: 'Vidyasagar Bhavan 2nd Floor Corridor Accounts for 38% of Plumbing Reports',
    description: 'A cluster of water cooler drain clogs and washroom backflow reports have centered around the Optics and Physics corridor feeder line.',
    affectedArea: 'Vidyasagar Bhavan (2nd Floor Corridor)',
    detectedDate: 'Active Clustering',
    linkedTickets: ['MC-2027-0108'],
    severity: 'WARNING',
    actionableRecommendation: 'Conduct a thorough camera inspection of the vertical drainage stack between 1st and 3rd floor rather than isolated faucet fixes.',
    metricImpact: 'Solves root cause for 4 recurring tickets',
  },
  {
    id: 'ins-03',
    type: 'PREVENTIVE_MAINTENANCE',
    title: 'Electrical Sub-panel Thermographic Audit Completed for Science Laboratories',
    description: 'Following the sparking incident in Chemistry Lab 3, thermal scans across adjacent physics and botany labs revealed 2 other aging 63A breakers operating near thermal limit.',
    affectedArea: 'Science & Tech Block (Labs 1-4)',
    detectedDate: 'Today',
    linkedTickets: ['MC-2027-0119'],
    severity: 'CRITICAL',
    actionableRecommendation: 'Procure 4 additional industrial-grade Schneider MCBs to proactively replace older circuits during the upcoming weekend maintenance window.',
    metricImpact: 'Mitigates potential lab shutdown during practical exams',
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Status Update on Your Report',
    message: 'Your ticket MC-2027-0104 (Centenary Projector) was updated to IN_PROGRESS by Subhashish Roy.',
    ticketNumber: 'MC-2027-0104',
    ticketId: 'iss-001',
    type: 'STATUS_CHANGE',
    read: false,
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: 'notif-2',
    title: 'Campus Alert: Chemistry Wing Corridor Power Isolation',
    message: 'Power temporarily isolated in Chem Lab 3 for planned sub-breaker replacement. Normal operations resume at 5:00 PM.',
    ticketNumber: 'MC-2027-0119',
    ticketId: 'iss-004',
    type: 'CAMPUS_ALERT',
    read: false,
    createdAt: new Date(Date.now() - 2.5 * 3600 * 1000).toISOString(),
  },
  {
    id: 'notif-3',
    title: 'Issue Resolved: Canteen Kitchen Exhaust',
    message: 'Ticket MC-2027-0095 has been successfully resolved and tested.',
    ticketNumber: 'MC-2027-0095',
    ticketId: 'iss-005',
    type: 'RESOLVED',
    read: true,
    createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
];
